$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error %O %S';
$bibtex = 'bibtex %O %B';
$out_dir = '.';
$aux_dir = 'build';
@generated_exts = (@generated_exts, 'bbl', 'bcf', 'run.xml', 'synctex.gz');
